config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts#, except: [:index]
  # get "posts",                to:"posts#index",                 as:"user_root"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container">
    <%= link_to "Blog", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav me-auto">
            <li>
                <%= link_to "Posts", posts_path, class:"nav-link" %>
            </li>
        </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
              <% if current_user.name %>
                Hola <%= current_user.name %>
              <% else %>
                Hola <%= current_user.email %>
              <% end %>
            <% else %>
                Inicia sesión o registrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= button_to "Cerrar Sesión", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %>
                <li><%= link_to "Iniciar Sesión", new_user_session_path, class:"dropdown-item" %></li>
                <li><%= link_to "Registro", new_user_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>